

export const SET_SEARCH = "SET_SEARCH";
export const SET_CUSTOM_PAGE = "SET_CUSTOM_PAGE";
export const SET_LOADING = "SET_LOADING";
export const SET_PER_PAGE = "SET_PER_PAGE";
export const SET_FILTERS="SET_FILTERS";
export const SET_PAGINATED_BATCHES ="SET_PAGINATED_BATCHES";
export const DELETE_BATCH="DELETE_BATCH";
